/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Christopher
 */
import javax.swing.*;
import Controller.CrearCuentaController;
import Model.Banco;
import Model.Clientes;

public class CrearCuenta extends javax.swing.JFrame {

    /**
     * Creates new form CrearCuenta
     */
    private JFrame frame;
    private JComboBox<String> clienteComboBox; // Lista desplegable para seleccionar el cliente
    private JTextField saldoField; // Campo para el saldo inicial
    private CrearCuentaController controller;

    
    public CrearCuenta(Banco banco, CrearCuentaController controller) {
       this.controller = controller;
        frame = new JFrame("Crear Cuenta");

        // Crear lista desplegable de clientes
        clienteComboBox = new JComboBox<>();
        for (Clientes cliente : banco.clientes.values()) {
            clienteComboBox.addItem(cliente.cui + " - " + cliente.nombre + " " + cliente.apellido);
        }

        saldoField = new JTextField(20); // Inicializar el campo de saldo
        JButton crearButton = new JButton("Crear Cuenta");

        crearButton.addActionListener(e -> {
            String cuiCliente = clienteComboBox.getSelectedItem().toString().split(" - ")[0]; // Obtener el CUI del cliente seleccionado
            try {
                double saldoInicial = Double.parseDouble(saldoField.getText());
                controller.crearCuenta(cuiCliente, saldoInicial);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(frame, "Saldo inicial inválido. Debe ser un número.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        });

        frame.setLayout(new BoxLayout(frame.getContentPane(), BoxLayout.Y_AXIS));
        frame.add(new JLabel("Seleccionar Cliente:"));
        frame.add(clienteComboBox);
        frame.add(new JLabel("Saldo Inicial:")); // Etiqueta para el saldo inicial
        frame.add(saldoField); // Campo para el saldo inicial
        frame.add(crearButton);
        frame.pack();
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jComboBox1 = new javax.swing.JComboBox<>();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
